### ISSUE TITLE
format() argument must be array, string given

### ISSUE THREAD

**Issue by You-Honey** [devgeniem/redipress#96]
Found this on the wp-admin index:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Geniem\RediPress\Utility::format() must be of the type array, string given, called in /var/www/project/web/app/plugins/redipress/src/Index/Index.php on line 656 and defined in /var/www/project/web/app/plugins/redipress/src/Utility.php:21 Stack trace: #0 /var/www/project/web/app/plugins/redipress/src/Index/Index.php(656): Geniem\RediPress\Utility::format('Unknown Index n...') #1 /var/www/project/web/app/plugins/redipress/src/Index/Index.php(554): Geniem\RediPress\Index\Index->convert_post(Object(WP_Post)) #2 /var/www/project/web/wp/wp-includes/class-wp-hook.php(289): Geniem\RediPress\Index\Index->index_single(66) #3 /var/www/project/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #4 /var/www/project/web/wp/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #5 /var/www/project/web/wp/wp-includes/taxonomy.php(2711): do_action('set_object_term...', 66, Array, Array, 'category', false, Array) #6 /var/www/project/web/wp/wp-includes/post.php(4816): wp_set_object_terms(66, Array, 'category', false) #7 /var/www/project/web/wp/wp-includes/post.php(4868): wp_set_post_terms(66, Array, 'category', false) #8 /var/www/project/web/wp/wp-includes/post.php(4088): wp_set_post_categories(66, Array) #9 /var/www/project/web/wp/wp-admin/includes/post.php(690): wp_insert_post(Array, false, false) #10 /var/www/project/web/wp/wp-admin/includes/dashboard.php(523): get_default_post_to_edit('post', true) #11 /var/www/project/web/wp/wp-admin/includes/template.php(1389): wp_dashboard_quick_press('', Array) #12 /var/www/project/web/wp/wp-admin/includes/dashboard.php(259): do_meta_boxes(Object(WP_Screen), 'side', '') #13 /var/www/project/web/wp/wp-admin/index.php(181): wp_dashboard() #14 {main} thrown in /var/www/project/web/app/plugins/redipress/src/Utility.php on line 21
```

Index was not created when this occurred.

Error disappeared after creating and indexing.

**Comment by jussipalanen** [comment]
The same issue was present when the index was not created.
The type needs to be `array, ' not  'string.' ...

Utility::format('Unknown index n...')
